name: Redline DOCX (LibreOffice headless)

on:
  workflow_dispatch:
    inputs:
      input_docx:
        description: 'Path to input .docx'
        required: true
        default: 'docs/input.docx'
      edits_csv:
        description: 'Path to edits CSV'
        required: true
        default: 'edits/edits_sample.csv'
      output_docx:
        description: 'Path to output .docx'
        required: true
        default: 'build/output.docx'

jobs:
  redline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LibreOffice and Python UNO
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice python3-uno libreoffice-dev
          # Set up LibreOffice environment
          export PYTHONPATH="/usr/lib/python3/dist-packages:$PYTHONPATH"

      # Test and setup Python UNO
      - name: Setup Python UNO
        id: lo_py
        run: |
          set -e

          # Set up environment for UNO
          export PYTHONPATH="/usr/lib/python3/dist-packages:/usr/lib/libreoffice/program:$PYTHONPATH"
          export UNO_PATH="/usr/lib/libreoffice/program"

          echo "Testing Python UNO import..."
          echo "PYTHONPATH: $PYTHONPATH"

          # Test if system Python can import uno
          if python3 -c "import sys; sys.path.insert(0, '/usr/lib/python3/dist-packages'); import uno; print('UNO import successful')" 2>/dev/null; then
            echo "✅ System Python with UNO works!"
            echo "path=python3" >> $GITHUB_OUTPUT
            echo "pythonpath=/usr/lib/python3/dist-packages:/usr/lib/libreoffice/program" >> $GITHUB_OUTPUT
          else
            echo "❌ UNO import failed. Debugging..."
            echo "Available packages in /usr/lib/python3/dist-packages:"
            ls -la /usr/lib/python3/dist-packages/ | grep -i uno || echo "No UNO packages found"
            echo "LibreOffice program directory:"
            ls -la /usr/lib/libreoffice/program/ | head -10 || echo "Program directory not found"
            
            # Try alternative paths
            if python3 -c "import sys; sys.path.append('/usr/lib/libreoffice/program'); import uno; print('UNO import successful with alternative path')" 2>/dev/null; then
              echo "✅ UNO works with alternative path"
              echo "path=python3" >> $GITHUB_OUTPUT
              echo "pythonpath=/usr/lib/libreoffice/program" >> $GITHUB_OUTPUT
            else
              echo "Failed to import UNO. Trying direct LibreOffice Python..."
              # Look for LibreOffice's own Python
              if [ -x "/usr/lib/libreoffice/program/python3" ]; then
                echo "Found LibreOffice Python"
                echo "path=/usr/lib/libreoffice/program/python3" >> $GITHUB_OUTPUT
                echo "pythonpath=" >> $GITHUB_OUTPUT
              else
                echo "No working Python with UNO found" >&2
                exit 1
              fi
            fi
          fi

      - name: Start LibreOffice headless service
        run: |
          # Start LibreOffice in headless mode with UNO listener
          echo "Starting LibreOffice headless service..."
          libreoffice --headless --invisible --nocrashreport --nodefault --nolockcheck --nologo --norestore --accept="socket,host=127.0.0.1,port=2002,urp;" &
          
          # Wait for LibreOffice to start
          echo "Waiting for LibreOffice to initialize..."
          sleep 5
          
          # Check if LibreOffice is listening
          if netstat -tln | grep -q ":2002 "; then
            echo "✅ LibreOffice is listening on port 2002"
          else
            echo "⚠️ LibreOffice may not be listening yet, continuing anyway..."
          fi

      - name: Run redline job
        env:
          LO_PY: ${{ steps.lo_py.outputs.path }}
          PYTHONPATH: ${{ steps.lo_py.outputs.pythonpath }}
          UNO_PATH: /usr/lib/libreoffice/program
        run: |
          mkdir -p build
          echo "Using Python: $LO_PY"
          echo "PYTHONPATH: $PYTHONPATH"

          # Set up environment and run script
          export PYTHONPATH="$PYTHONPATH"
          export UNO_PATH="/usr/lib/libreoffice/program"
          
          # Debug: Check if files exist
          echo "Input file exists: $(test -f '${{ github.event.inputs.input_docx }}' && echo 'YES' || echo 'NO')"
          echo "CSV file exists: $(test -f '${{ github.event.inputs.edits_csv }}' && echo 'YES' || echo 'NO')"
          
          # Run the script (LibreOffice should already be running)
          "$LO_PY" scripts/apply_tracked_edits_libre.py \
            --in "${{ github.event.inputs.input_docx }}" \
            --csv "${{ github.event.inputs.edits_csv }}" \
            --out "${{ github.event.inputs.output_docx }}"

      - name: Stop LibreOffice service
        if: always()
        run: |
          echo "Stopping LibreOffice headless service..."
          pkill -f "libreoffice.*--headless" || echo "LibreOffice already stopped"

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: redlined-docx
          path: ${{ github.event.inputs.output_docx }}
