name: Redline DOCX (LibreOffice headless)

on:
  workflow_dispatch:
    inputs:
      input_docx:
        description: 'Path to input .docx'
        required: true
        default: 'docs/input.docx'
      edits_csv:
        description: 'Path to edits CSV'
        required: true
        default: 'edits/edits_sample.csv'
      output_docx:
        description: 'Path to output .docx'
        required: true
        default: 'build/output.docx'

jobs:
  redline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LibreOffice and Python UNO
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice python3-uno
          # Also try installing pyuno via pip as backup
          python3 -m pip install --user pyuno || true

      # Find LibreOffice Python (different locations on different Ubuntu versions)
      - name: Find LibreOffice Python
        id: lo_py
        run: |
          set -e
          # Try different possible locations
          POSSIBLE_PATHS=(
            "/usr/lib/libreoffice/program/python3"
            "/usr/lib/libreoffice/program/python"
            "/usr/bin/python3"
            "python3"
          )
          
          LO_PY=""
          for path in "${POSSIBLE_PATHS[@]}"; do
            if command -v "$path" >/dev/null 2>&1; then
              # Test if uno module is available
              if "$path" -c "import uno" 2>/dev/null; then
                LO_PY="$path"
                echo "Found working LibreOffice Python: $LO_PY"
                break
              fi
            fi
          done
          
          if [ -z "$LO_PY" ]; then
            echo "No working LibreOffice Python found. Testing system Python with pip install..."
            # Try installing pyuno for system Python
            python3 -m pip install --user pyuno || true
            if python3 -c "import uno" 2>/dev/null; then
              LO_PY="python3"
              echo "System Python works with UNO after pyuno install"
            else
              echo "Failed to find working Python with UNO support" >&2
              exit 1
            fi
          fi
          
          echo "path=$LO_PY" >> $GITHUB_OUTPUT

      - name: Run redline job
        env:
          LO_PY: ${{ steps.lo_py.outputs.path }}
        run: |
          mkdir -p build
          "$LO_PY" scripts/apply_tracked_edits_libre.py \
            --in "${{ github.event.inputs.input_docx }}" \
            --csv "${{ github.event.inputs.edits_csv }}" \
            --out "${{ github.event.inputs.output_docx }}" \
            --launch

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: redlined-docx
          path: ${{ github.event.inputs.output_docx }}
